/*****************************************
* Copyright (C) 2020 * Ltd. All rights reserved.
* 
* File name   : xservice_hsm_mgr_event.h
* Author      : longbin
* Created date: 2020-08-05 14:30:41
* Description : 
*
*******************************************/

#ifndef __XSERVICE_HSM_MGR_EVENT_H__
#define __XSERVICE_HSM_MGR_EVENT_H__

/**
 * The following was auto-generated by gen_hsm;
 * it declares the events used by statecharts within the model.
 */
#define MODEL_EVENT_IDS\
   X(EVT_TypedKeyDot)\
   X(EVT_TypedKeyEnter)\
   X(EVT_TypedKeyNumber0)\
   X(EVT_TypedKeyNumber1_9)\
   X(EVT_TypedKeyOther)\
   X(EVT_TypedKeyPound)\
   X(EVT_TypedKeySign)

#undef X
#define X(evt) evt,
typedef enum
{
   MODEL_EVENT_IDS
   MODEL_EVENT_IDS_NUM_EVENTS
}
Model_Event_Ids_T;

#undef X
#define X(id) case (id): { return #id; }
#define EVENT2STRS MODEL_EVENT_IDS

#endif

